header:
  version: 14

distro: luckfox
machine: luckfox-pico-ultra-w
target: luckfox-image

defaults:
  repos:
    branch: wrynose

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: "2.18"
    path: sources/bitbake
    layers:
      .: disabled

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    path: sources/openembedded-core
    layers:
      meta:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    path: sources/meta-yocto
    layers:
      meta-poky:
      meta-yocto-bsp:

  yocto-docs:
    url: https://git.yoctoproject.org/yocto-docs
    path: sources/yocto-docs
    layers:
      .: disabled

  luckfox-docs:
    url: https://github.com/LuckfoxTECH/Luckfox-Pico-docs
    branch: main
    path: sources/luckfox-docs
    layers:
      .: disabled

  meta-luckfox-bsp:
    path: sources/meta-luckfox/meta-luckfox-bsp

  meta-luckfox-distro:
    path: sources/meta-luckfox/meta-luckfox-distro

